### ISSUE TITLE
Project with null inner collections

### ISSUE THREAD

**Issue by gius** [fluentsprings/ExpressMapper#107]
Calling `Project` on entity with collection property set to null throws exception.

Example code:
```
void Main()
{
	ExpressMapper.Mapper.Register<Source, Target>();

	var data = new List<Source>
	{
		new Source { ID = 1, Name = "First" }, // This causes error!
		new Source { ID = 2, Name = "Second", Items = new List<SourceItem>
			{
				new SourceItem { Name = "Inner" }
			}
		}
	};
	
	var query = data.AsQueryable();
	
	var result = ExpressMapper.Mapper.Instance.Project<Source, Target>(query);
	result.Dump("result");
}

public class Source
{
	public int ID { get; set; }
	public string Name { get; set; }
	public List<SourceItem> Items { get; set; }
}

public class SourceItem
{
	public string Name { get; set; }
}

public class Target
{
	public int ID { get; set; }
	public string Name { get; set; }
	public List<TargetItem> Items { get; set; }
}

public class TargetItem
{
	public string Name { get; set; }
}
```

When `First` item is removed from the collection, the `Project` function works properly.

Exceptions details:
ArgumentNullException - Value cannot be null. Parameter name: source
StackTrace:  
```
at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
at lambda_method(Closure , Source )
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by anisimovyuriy** [comment]
Dear @gius,

Thanks a lot for your input - I'll get back to your shortly.

Thanks!

**Comment by RudeySH** [comment]
Any update on this? I'm having this issue as well.
