### ISSUE TITLE
Nuget - Could not load type 'ExpressMapper.TypeExtensions' from assembly 'ExpressMapper, Version=1.8.2.0

### ISSUE THREAD

**Issue by sridharrajan** [fluentsprings/ExpressMapper#112]
Hi,

You are doing Excellent job!!! Thanks for releasing Version 1.8.2.

I am getting below error after downloading from nuget 1.8.2. Please help me to solve this.

Could not load type 'ExpressMapper.TypeExtensions' from assembly 'ExpressMapper, Version=1.8.2.0, Culture=neutral, PublicKeyToken=ac363faa09311ba0'.
   at ExpressMapper.MappingServiceProvider.RegisterInternal[T,TN](Boolean memberCaseInsensitive)
   at ExpressMapper.MappingServiceProvider.Register[T,TN]() in C:\Source\ExpressMapper\ExpressMapper NET40\MappingServiceProvider.cs:line 62
   at ExpressMapper.Mapper.Register[T,TN]() in C:\Source\ExpressMapper\ExpressMapper NET40\Mapper.cs:line 68
   at ConsoleApplication1.Program.Main(String[] args) in d:\Sridhar\Sample\SriSample2\ConsoleApplication1\Program.cs:line 14
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

Also I have added below in App.Config.
[SriSample2.zip](https://github.com/fluentsprings/ExpressMapper/files/466407/SriSample2.zip)

`<runtime>    
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="ExpressMapper.TypeExtensions" publicKeyToken="ac363faa09311ba0" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.8.2.0" newVersion="1.8.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="ExpressMapper" publicKeyToken="ac363faa09311ba0" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.8.2.0" newVersion="1.8.2.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>`

**Comment by anisimovyuriy** [comment]
Thanks a lot @sridharrajan - it's been taken care of already. I'm going to release a fix!

**Comment by anisimovyuriy** [comment]
Fixed and included in 1.8.3 and released!
